Repository green-bowl/greenbowl-backend, pull requests merged in 2025-02, with the labels that each got.

#4 [TEAM15-23] chore(recommendation): Recommendation Service 모듈 추가
  .env
  docker-compose.yml
  recommendation-service/gradle/wrapper/gradle-wrapper.jar
  recommendation-service/gradle/wrapper/gradle-wrapper.properties
  recommendation-service/recommendation-adapters/build.gradle
  recommendation-service/recommendation-adapters/gradle/wrapper/gradle-wrapper.jar
  recommendation-service/recommendation-adapters/gradle/wrapper/gradle-wrapper.properties
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/RecommendationApplication.java
  recommendation-service/recommendation-adapters/src/main/resources/application.yml
  recommendation-service/recommendation-adapters/src/test/java/com/greenbowl/greenbowlserver/recommendation/RecommendationApplicationTests.java
  recommendation-service/recommendation-application/build.gradle
  recommendation-service/recommendation-application/gradle/wrapper/gradle-wrapper.jar
  recommendation-service/recommendation-application/gradle/wrapper/gradle-wrapper.properties
  recommendation-service/recommendation-domain/build.gradle
  recommendation-service/recommendation-domain/gradle/wrapper/gradle-wrapper.jar
  recommendation-service/recommendation-domain/gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: configuration

#8 [TEAM15-197] chore(logging): 전체 프로젝트의 로깅 프로세스 추가
  common/src/main/java/com/greenbowl/greenbowlserver/common/adapter/in/interception/LoggingInterceptor.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/application/aop/LogMessage.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/application/aop/LoggingAspect.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/configuration/InterceptorConfig.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/utility/PerformanceMeasurer.java
  common/src/main/resources/META-INF/spring.factories
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/configuration/CommonConfig.java
  recommendation-service/recommendation-adapters/src/main/resources/application.yml
  recommendation-service/recommendation-adapters/src/main/resources/logback-spring.xml
Labels: enhancement, configuration

#10 [TEAM15-205] feat(exception): 공통 예외 처리를 위한 Exception Handler 및 공통 예외 추가 (Common 모듈)
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/ErrorResponse.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/ExceptionMessage.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/GlobalExceptionHandler.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/invalidvalue/InvalidEmailException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/invalidvalue/InvalidIdException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/invalidvalue/InvalidTargetTypeException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/invalidvalue/InvalidValueException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/invalidvalue/ParsingBooleanException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/invalidvalue/ParsingLocalDateTimeException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/novalue/EmailNoValueException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/novalue/IdNoValueException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/novalue/NoValueException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/numberformat/ParsingByteException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/numberformat/ParsingDoubleException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/numberformat/ParsingFloatException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/numberformat/ParsingIntegerException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/numberformat/ParsingLongException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/excpeption/illegalargument/numberformat/ParsingShortException.java
Labels: enhancement

#12 [TEAM15-214] chore(entity): 엔티티의 일반적인 컬럼을 자동으로 관리하는 BaseEntity와 BaseGeneralEntity 클래스 추가 (Common 모듈)
  common/src/main/java/com/greenbowl/greenbowlserver/common/adapter/out/persistence/audit/BaseEntity.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/adapter/out/persistence/audit/BaseGeneralEntity.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/configuration/AuditConfig.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/utility/EntityConstant.java
Labels: enhancement, configuration

#18 [TEAM15-220] chore(format): 포맷 검증과 변환을 위한 유틸리티 클래스 추가 (Common 모듈)
  common/src/main/java/com/greenbowl/greenbowlserver/common/adapter/in/InputFormatValidator.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/TargetType.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/ErrorResponse.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/ExceptionMessage.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/GlobalExceptionHandler.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/invalidvalue/InvalidEmailException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/invalidvalue/InvalidIdException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/invalidvalue/InvalidTargetTypeException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/invalidvalue/InvalidValueException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/invalidvalue/ParsingBooleanException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/invalidvalue/ParsingLocalDateTimeException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/novalue/EmailNoValueException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/novalue/IdNoValueException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/novalue/NoValueException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/numberformat/ParsingByteException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/numberformat/ParsingDoubleException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/numberformat/ParsingFloatException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/numberformat/ParsingIntegerException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/numberformat/ParsingLongException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/illegalargument/numberformat/ParsingShortException.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/utility/FormatConverter.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/utility/FormatValidator.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/utility/RegularExpressionConstant.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/configuration/CommonConfig.java
Labels: enhancement

#19 [TEAM15-231] chore(recommendation): Recommendation Service에 API 문서화를 위한 Swagger UI 추가
  recommendation-service/recommendation-adapters/build.gradle
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/configuration/SwaggerConfig.java
  recommendation-service/recommendation-adapters/src/main/resources/application.yml
  recommendation-service/recommendation-domain/build.gradle
Labels: configuration

#20 [TEAM15-234] chore(recommendation): 클라이언트는 Swagger 문서를 통해 Recommendation Service의 이용 가이드를 확인할 수 있다
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/configuration/SwaggerConfig.java
Labels: documentation, enhancement

#26 [TEAM15-372] fix(fridge): CreateCategoryItemRequest Validation 수정 (#25)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/request/CreateCategoryItemRequest.java
Labels: bug

#30 [TEAM15-383] docs(fridge): Swagger API 문서화 (#29)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/ApiConstant.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/request/CreateCategoryItemRequest.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/request/CreateIngredientRequest.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/request/DeleteCategoryItemRequest.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/request/DeleteIngredientRequest.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/request/UpdateIngredientRequest.java
Labels: documentation

#32 [TEAM15-384] feat(fridge): API endpoint 변경 (#31)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/CreateCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/CreateIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/DeleteCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/DeleteIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/GetCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/GetIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/UpdateIngredientController.java
Labels: enhancement

#34 [TEAM15-385] feat(fridge): changed Domain type (#33)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/request/CreateIngredientRequest.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/GetIngredientResponse.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/UpdateIngredientResponse.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/categoryitem/CategoryItemJpaEntity.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/ingredient/IngredientJpaEntity.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/IngredientResult.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/command/CreateIngredientCommand.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/command/UpdateIngredientCommand.java
  fridge-service/fridge-domain/src/main/java/com/greenbowl/greenbowlserver/fridge/domain/Ingredient.java
  fridge-service/fridge-domain/src/main/java/com/greenbowl/greenbowlserver/fridge/domain/wrapper/StorageMethod.java
Labels: enhancement

#37 [TEAM15-385] feat(fridge): allow cors (#36)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/config/CorsConfig.java
Labels: configuration

#39 [TEAM15-392] feat(fridge): fridge service Category별 조회 기능 구현 (#38)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/config/SwaggerConfig.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/GetCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/GetCategoryItemBySequenceResponse.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/categoryitem/CategoryItemJpaRepository.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/categoryitem/CategoryItemPersistenceAdapter.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/usecase/GetCategoryItemUseCase.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/out/GetCategoryItemPort.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/GetCategoryItemService.java
Labels: enhancement

#41 [TEAM15-396] feat(eureka): eureka 모듈 추가 (#40)
  eureka-service/eureka/build.gradle
  eureka-service/eureka/gradle/wrapper/gradle-wrapper.jar
  eureka-service/eureka/gradle/wrapper/gradle-wrapper.properties
  eureka-service/eureka/src/main/java/com/greenbowl/greenbowlserver/eureka/EurekaApplication.java
  eureka-service/eureka/src/main/resources/application.yml
  eureka-service/eureka/src/main/resources/logback-spring.xml
  eureka-service/eureka/src/test/java/com/greenbowl/greenbowlserver/eureka/EurekaApplicationTests.java
  eureka-service/gradle/wrapper/gradle-wrapper.jar
  eureka-service/gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: enhancement

#45 [TEAM15-398] feat(fridge): fridge service eureka client 적용 (#44)
  fridge-service/fridge-adapters/build.gradle
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/FridgeApplication.java
  fridge-service/fridge-adapters/src/main/resources/application.yml
Labels: enhancement

#47 [TEAM15-397] feat(fridge): fridge service response 수정 (#46)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/GetCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/GetCategoryItemBySequenceResponse.java
Labels: enhancement

#48 [TEAM15-397] feat(fridge): fridge service Category별 조회 Response 값 추가
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/GetCategoryItemBySequenceResponse.java
Labels: enhancement

#55 [TEAM15-436] chore(recipe): Recipe Service 모듈 추가
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/excpeption/GlobalExceptionHandler.java
  docker-compose.yml
  recipe-service/recipe-adapters/build.gradle
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/RecipeApplication.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/configuration/CommonConfig.java
  recipe-service/recipe-adapters/src/main/resources/application.yml
  recipe-service/recipe-adapters/src/main/resources/logback-spring.xml
  recipe-service/recipe-adapters/src/test/java/com/greenbowl/greenbowlserver/recipe/RecipeApplicationTests.java
  recipe-service/recipe-application/build.gradle
  recipe-service/recipe-domain/build.gradle
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/configuration/SwaggerConfig.java
  settings.gradle
Labels: configuration

#56 [TEAM15-441] chore(recipe): Recipe Service에 API 문서화를 위한 Swagger UI 추가
  recipe-service/recipe-adapters/build.gradle
Labels: configuration

#57 [TEAM15-444] chore(recipe): 클라이언트는 Swagger 문서를 통해 Recipe Service의 이용 가이드를 확인할 수 있다
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/configuration/SwaggerConfig.java
Labels: documentation, configuration

#58 [TEAM15-312] fix(audit): 다른 서비스에서 Common 모듈의 Audit 기능을 적용할 수 없는 문제 해결
  common/src/main/resources/META-INF/spring.factories
Labels: bug

#60 [TEAM15-483] chore(cors): 레시피 서비스 CORS 활성화
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/configuration/WebConfig.java
  recipe-service/recipe-adapters/src/main/resources/application.yml
Labels: configuration, deployment

#61 [TEAM15-448] feat(recipe): 클라이언트는 레시피 서버를 통해 요청한 레시피 정보를 저장할 수 있다
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/AddBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/mapper/RecipeRequestToCommandMapper.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/request/AddRecipeRequest.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/EmbeddableNutrition.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeIngredientJpaEntity.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeJpaEntity.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipePersistenceAdapter.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeRepository.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/command/CreateRecipeCommand.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/mapper/RecipeCommandToDomainMapper.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/usecase/CreateRecipeUseCase.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/out/SaveRecipePort.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/service/CreateRecipeService.java
  recipe-service/recipe-domain/src/main/java/com/greenbowl/greenbowlserver/recipe/configuration/CommonConfig.java
  recipe-service/recipe-domain/src/main/java/com/greenbowl/greenbowlserver/recipe/domain/Nutrition.java
  recipe-service/recipe-domain/src/main/java/com/greenbowl/greenbowlserver/recipe/domain/RecipIngredient.java
  recipe-service/recipe-domain/src/main/java/com/greenbowl/greenbowlserver/recipe/domain/Recipe.java
Labels: enhancement

#62 [TEAM15-453] feat(recipe): 클라이언트는 레시피 서버를 통해 요청한 상세 레시피 정보를 저장할 수 있다
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/request/AddDetailedRecipeRequest.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/request/NutritionRequest.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/request/UsedIngredientRequest.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/command/CreateDetailedRecipeCommand.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/command/IngredientCommand.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/command/NutritionCommand.java
Labels: enhancement

#63 [TEAM15-453] feat(recipe): 누락된 변경사항 추가
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/AddBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/mapper/RecipeRequestToCommandMapper.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeIngredientJpaEntity.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeJpaEntity.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/mapper/RecipeCommandToDomainMapper.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/usecase/CreateRecipeUseCase.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/service/CreateRecipeService.java
  recipe-service/recipe-domain/src/main/java/com/greenbowl/greenbowlserver/recipe/domain/Nutrition.java
  recipe-service/recipe-domain/src/main/java/com/greenbowl/greenbowlserver/recipe/domain/Recipe.java
  recipe-service/recipe-domain/src/main/java/com/greenbowl/greenbowlserver/recipe/domain/RecipeIngredient.java
Labels: enhancement

#65 [TEAM15-494] feat(recipe): 클라이언트는 레시피 서버를 통해 북마크에 저장된 레시피 정보를 조회할 수 있다
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/GetBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/response/GetRecipeResponse.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/response/NutritionResponse.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/response/RecipeIngredientResponse.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/mapper/RecipeJpaEntityToDomainMapper.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeIngredientJpaEntity.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeJpaEntity.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipePersistenceAdapter.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeRepository.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/exception/ExceptionMessage.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/exception/RecipeNotFoundException.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/usecase/GetRecipeUseCase.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/out/FindRecipePort.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/service/GetRecipeService.java
  recipe-service/recipe-domain/src/main/java/com/greenbowl/greenbowlserver/recipe/domain/Recipe.java
Labels: enhancement

#67 [TEAM15-502] feat(recipe): 클라이언트는 레시피 서버를 통해 특정 회원의 북마크에 저장된 레시피 목록을 최신 순으로 조회할 수 있다
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/GetBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/response/GetDetailedRecipeResponse.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/response/GetRecipeResponse.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipePersistenceAdapter.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeRepository.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/usecase/GetRecipeUseCase.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/out/FindRecipePort.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/service/GetRecipeService.java
Labels: enhancement
