Repository green-bowl/greenbowl-backend, pull requests merged in 2025-03, with the labels that each got.

#69 [TEAM15-507] chore(common): 공통 커스텀 어노테이션 추가
  common/src/main/java/com/greenbowl/greenbowlserver/common/adapter/in/WebAdapter.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/adapter/out/PersistenceAdapter.java
  common/src/main/java/com/greenbowl/greenbowlserver/common/application/UseCase.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/configuration/SwaggerConfig.java
Labels: enhancement, configuration

#74 [TEAM15-512] chore(common): User Service 모듈 추가
  docker-compose.yml
  settings.gradle
  user-service/user-adapters/build.gradle
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/UserApplication.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/configuration/WebConfig.java
  user-service/user-adapters/src/main/resources/application.yml
  user-service/user-adapters/src/main/resources/logback-spring.xml
  user-service/user-adapters/src/test/java/com/greenbowl/greenbowlserver/user/UserAplicationTests.java
  user-service/user-application/build.gradle
  user-service/user-domain/build.gradle
Labels: configuration

#75 [TEAM15-518] docs(user): User Service에 API 문서화를 위한 Swagger UI 추가
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/configuration/SwaggerConfig.java
Labels: documentation, configuration

#76 [TEAM15-521] docs(user): 클라이언트는 Swagger 문서를 통해 User Service의 이용 가이드를 확인할 수 있다
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/configuration/SwaggerConfig.java
Labels: documentation

#78 [TEAM15-535] feat(fridge): fridge service default-category 기능 구현 (#77)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/defaultcategoryitem/DefaultCategoryItemJpaEntity.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/defaultcategoryitem/DefaultCategoryItemJpaRepository.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/defaultcategoryitem/DefaultCategoryItemPersistenceAdapter.java
  fridge-service/fridge-adapters/src/main/resources/application.yml
  fridge-service/fridge-adapters/src/main/resources/data.sql
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/usecase/GetDefaultCategoryItemUseCase.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/out/GetDefaultCategoryItemPort.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/GetDefaultCategoryItemService.java
  fridge-service/fridge-domain/src/main/java/com/greenbowl/greenbowlserver/fridge/domain/DefaultCategoryItem.java
Labels: enhancement

#80 [TEAM15-536] feat(fridge): fridge service default ingredient 기능 구현 (#79)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/CreateDefaultIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/DeleteDefaultIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/UpdateDefaultIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/defaultingredient/DefaultIngredientJpaEntity.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/defaultingredient/DefaultIngredientJpaRepository.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/defaultingredient/DefaultIngredientPersistenceAdapter.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/DefaultIngredientResult.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/command/CreateDefaultIngredientCommand.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/mapper/DefaultIngredientCommandToDomainMapper.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/usecase/CreateDefaultIngredientUseCase.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/usecase/DeleteDefaultIngredientUseCase.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/usecase/GetDefaultIngredientUseCase.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/usecase/UpdateDefaultIngredientUseCase.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/out/CreateDefaultIngredientPort.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/out/DeleteDefaultIngredientPort.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/out/GetDefaultIngredientPort.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/out/UpdateDefaultIngredientPort.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/CreateDefaultIngredientService.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/DeleteDefaultIngredientService.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/GetDefaultIngredientService.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/UpdateDefaultIngredientService.java
  fridge-service/fridge-domain/src/main/java/com/greenbowl/greenbowlserver/fridge/domain/DefaultIngredient.java
Labels: enhancement

#82 [TEAM15-537] feat(fridge):Fridge Service 로직 개선 (#81)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/CreateIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/DeleteIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/GetCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/GetIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/CreateIngredientResponse.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/GetCategoryItemBySequenceResponse.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/GetIngredientResponse.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/UpdateIngredientResponse.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/mapper/FridgeJpaEntityToDomainMapper.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/categoryitem/CategoryItemJpaRepository.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/ingredient/IngredientJpaRepository.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/ingredient/IngredientPersistenceAdapter.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/in/usecase/CreateIngredientUseCase.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/port/out/CreateIngredientPort.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/CreateIngredientService.java
Labels: enhancement

#84 [TEAM15-539] config: docker compose 수정 (#83)
  docker-compose.yml
Labels: configuration

#85 [TEAM15-525] feat(user): 클라이언트는 회원 서버를 통해 로그인 서비스를 이용할 수 있다
  common/src/main/java/com/greenbowl/greenbowlserver/common/utility/LogConstant.java
  recipe-service/recipe-adapters/src/main/resources/application.yml
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/ApiConstant.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/configuration/WebSecurityConfig.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/controller/AuthenticationController.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/mapper/UserRequestToCommandMapper.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/request/SignInRequest.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/response/SignInResponse.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/security/CustomAuthenticationEntryPoint.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/security/JwtAuthenticationFilter.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/out/mapper/UserJpaEntityToDomainMapper.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/out/persistence/security/JwtTokenProvider.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/out/persistence/user/UserJpaEntity.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/out/persistence/user/UserPersistenceAdapter.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/out/persistence/user/UserRepository.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/configuration/CommonConfig.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/exception/ExceptionMessage.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/exception/UserNotFoundException.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/port/in/AuthenticationResult.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/port/in/command/SignInCommand.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/port/in/usecase/AuthenticationUseCase.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/port/in/usecase/GetUserUseCase.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/port/in/usecase/SignUpUseCase.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/port/out/AuthenticationPort.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/port/out/FindUserPort.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/port/out/SignUpPort.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/service/AuthenticationService.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/service/GetUserService.java
  user-service/user-application/src/main/java/com/greenbowl/greenbowlserver/user/service/SignUpService.java
  user-service/user-domain/src/main/java/com/greenbowl/greenbowlserver/user/configuration/CommonConfig.java
  user-service/user-domain/src/main/java/com/greenbowl/greenbowlserver/user/domain/User.java
  user-service/user-domain/src/main/java/com/greenbowl/greenbowlserver/user/domain/exception/message/BlankExceptionMessage.java
  user-service/user-domain/src/main/java/com/greenbowl/greenbowlserver/user/domain/exception/message/InvalidExceptionMessage.java
  user-service/user-domain/src/main/java/com/greenbowl/greenbowlserver/user/domain/exception/message/NotFoundExceptionMessage.java
  user-service/user-domain/src/main/java/com/greenbowl/greenbowlserver/user/domain/security/CustomUserDetails.java
  user-service/user-domain/src/main/java/com/greenbowl/greenbowlserver/user/domain/wrapper/Email.java
  user-service/user-domain/src/main/java/com/greenbowl/greenbowlserver/user/domain/wrapper/WrapperAccessor.java
Labels: enhancement, configuration

#87 [TEAM15-541] fix: docker compose 수정 (#86)
  .gitignore
  docker-compose.yml
Labels: bug

#88 [TEAM15-541] fix: application.yml 수정 (#86)
  fridge-service/fridge-adapters/src/main/resources/application.yml
Labels: bug

#93 [TEAM15-470] feat(recipe): 클라이언트는 레시피 서버를 통해 요청한 레시피 정보를 삭제할 수 있다
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/CancelBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeJpaEntity.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipePersistenceAdapter.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeRepository.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/usecase/RemoveRecipeUseCase.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/out/DeleteRecipePort.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/service/RemoveRecipeService.java
Labels: enhancement

#96 [TEAM15-549] feat(user): 회원 서비스의 로그인 응답 시 엑세스 토큰을 헤더에 보내도록 변경
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/controller/AuthenticationController.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/response/SignInResponse.java
  user-service/user-adapters/src/main/resources/application.yml
Labels: enhancement

#97 [TEAM15-546] feat(recipe): 레시피 서버의 회원 북마크 추가 및 북마크 목록 조회 기능에 실제 회원 ID 적용
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/AddBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/GetBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/mapper/RecipeJpaEntityToDomainMapper.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeJpaEntity.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipePersistenceAdapter.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeRepository.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/mapper/RecipeCommandToDomainMapper.java
  recipe-service/recipe-domain/src/main/java/com/greenbowl/greenbowlserver/recipe/domain/Recipe.java
  user-service/user-adapters/src/main/resources/application.yml
Labels: enhancement

#98 [TEAM15-251] 클라이언트는 Swagger 문서를 통해 레시피 추천 서비스 이용 가이드를 확인할 수 있다
  common/src/main/java/com/greenbowl/greenbowlserver/common/utility/ApiConstant.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/AddBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/CancelBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/GetBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/request/AddDetailedRecipeRequest.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/request/AddRecipeRequest.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/request/NutritionRequest.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/request/UsedIngredientRequest.java
Labels: documentation

#100 [TEAM15-556] feat(recipe): 클라이언트는 레시피 서버를 통해 요청한 ID를 가진 레시피 정보를 삭제할 수 있다
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/CancelBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/GetBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/utility/ApiConstant.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipePersistenceAdapter.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeRepository.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/configuration/SwaggerConfig.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/usecase/GetRecipeUseCase.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/usecase/RemoveRecipeUseCase.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/out/FindRecipePort.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/service/GetRecipeService.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/service/RemoveRecipeService.java
Labels: enhancement

#102 [TEAM15-245] feat(recommendation): 클라이언트는 Recommendation Service에서 Push된 LLM 스트리밍 데이터를 수신할 수 있다
  common/src/main/java/com/greenbowl/greenbowlserver/common/utility/ApiConstant.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/CancelBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/GetBookmarkRecipeController.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/request/AddDetailedRecipeRequest.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/request/AddRecipeRequest.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/utility/ApiConstant.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/configuration/SwaggerConfig.java
  recommendation-service/recommendation-adapters/build.gradle
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/configuration/WebConfig.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/controller/RecommendLlmRecipeController.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/mapper/RecommendationRequestToCommandMapper.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/request/RecipeOptionsRequest.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/response/ResponseGenerator.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/response/StreamingProcessor.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/web/LLMRequest.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/web/client/LLMStreamingClient.java
  recommendation-service/recommendation-adapters/src/main/resources/application.yml
  recommendation-service/recommendation-application/build.gradle
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/command/RecipeOptionsCommand.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/mapper/RecommendationCommandToDomainMapper.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/usecase/RecommendLlmRecipeUseCase.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/out/ReceiveLLMStreamingPort.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/service/RecommendLlmRecipeService.java
  recommendation-service/recommendation-domain/src/main/java/com/greenbowl/greenbowlserver/recommendation/configuration/CommonConfig.java
  recommendation-service/recommendation-domain/src/main/java/com/greenbowl/greenbowlserver/recommendation/domain/RecipeOptions.java
Labels: enhancement

#104 [TEAM15-251] docs(recommendation): 클라이언트는 Swagger 문서를 통해 레시피 추천 서비스 이용 가이드를 확인할 수 있다
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/controller/RecommendLlmRecipeController.java
Labels: documentation

#108 [TEAM15-280] feat(recommendation): 클라이언트는 Recommendation Service에서 전송된 JSON 포맷의 메뉴 정보 LLM 데이터를 수신할 수 있다
  common/src/main/java/com/greenbowl/greenbowlserver/common/utility/ApiConstant.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/configuration/SwaggerConfig.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/configuration/WebConfig.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/controller/RecommendLlmMenuController.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/controller/RecommendLlmRecipeController.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/mapper/RecommendationRequestToCommandMapper.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/request/MenuOptionsRequest.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/request/RecipeOptionsRequest.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/configuration/RestTemplateConfig.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/configuration/WebClientConfig.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/request/ApiConstant.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/request/LlmRequest.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/web/LLMRequest.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/web/client/LlmJsonClient.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/web/client/LlmStreamingClient.java
  recommendation-service/recommendation-adapters/src/main/resources/application.yml
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/command/MenuOptionsCommand.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/command/RecipeOptionsCommand.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/mapper/RecommendationCommandToDomainMapper.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/usecase/RecommendLlmMenuUseCase.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/usecase/RecommendLlmRecipeUseCase.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/out/ReceiveLLMStreamingPort.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/out/ReceiveLlmJsonPort.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/out/ReceiveLlmStreamingPort.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/service/RecommendLlmMenuService.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/service/RecommendLlmRecipeService.java
  recommendation-service/recommendation-domain/src/main/java/com/greenbowl/greenbowlserver/recommendation/domain/MenuOptions.java
  recommendation-service/recommendation-domain/src/main/java/com/greenbowl/greenbowlserver/recommendation/domain/RecipeOptions.java
Labels: enhancement

#109 [TEAM15-586] docs(recommendation): 클라이언트는 Swagger 문서를 통해 메뉴 추천 서비스 이용 가이드를 확인할 수 있다
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/controller/RecommendLlmMenuController.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/web/client/LlmJsonClient.java
  recommendation-service/recommendation-adapters/src/main/resources/application.yml
Labels: documentation

#110 [TEAM15-590] feat(recommendation): 클라이언트는 Recommendation Service에서 전송된 JSON 포맷의 상세 메뉴 정보 LLM 데이터를 수신할 수 있다
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/controller/RecommendLlmMenuController.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/controller/RecommendLlmRecipeController.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/mapper/RecommendationRequestToCommandMapper.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/request/DetailedMenuOptionsRequest.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/web/client/LlmJsonClient.java
  recommendation-service/recommendation-adapters/src/main/resources/application.yml
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/command/DetailedMenuOptionsCommand.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/mapper/RecommendationCommandToDomainMapper.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/usecase/RecommendLlmMenuUseCase.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/service/RecommendLlmMenuService.java
  recommendation-service/recommendation-domain/src/main/java/com/greenbowl/greenbowlserver/recommendation/domain/DetailedMenuOptions.java
Labels: enhancement

#111 [TEAM15-597] docs(recommendation): 클라이언트는 Swagger 문서를 통해 상세 메뉴 추천 서비스 이용 가이드를 확인할 수 있다
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/controller/RecommendLlmMenuController.java
Labels: documentation

#112 [TEAM15-569] chore(orchestration): k8s, AWS EKS 적용
  k8s/base/namespace.yml
  k8s/database/postgres-config.yml
  k8s/database/postgres-pvc.yml
  k8s/database/postgres-secret.yml
  k8s/database/postgres-service.yml
  k8s/database/postgres-statefulset.yml
  k8s/deployment/fridge-adapters-deployment.yml
  k8s/deployment/recipe-adapters-deployment.yml
  k8s/deployment/recommendation-adapters-deployment.yml
  k8s/deployment/user-adapters-deployment.yml
  k8s/service/fridge-adapters-service.yml
  k8s/service/recipe-adapters-service.yml
  k8s/service/recommendation-adapters-service.yml
  k8s/service/user-adapters-service.yml
Labels: configuration, deployment

#114 [TEAM15-605] fix(recommendation): AI 서버로 조리 시간 제한이 중복 전송되는 문제 해결
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/port/in/mapper/RecommendationCommandToDomainMapper.java
Labels: bug

#118 [TEAM15-607] feat(fridge): 커스텀 예외처리 적용 (#117)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/categoryitem/CategoryItemPersistenceAdapter.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/aop/FridgeLoggingAspect.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/exception/NotFoundCategoryItemException.java
  fridge-service/fridge-domain/src/main/java/com/greenbowl/greenbowlserver/fridge/domain/exception/DuplicateCategoryException.java
Labels: enhancement

#121 [TEAM15-608] feat(fridge): Fridge Service 카테고리별 조회 기능 로직 수정 (#120)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/categoryitem/CategoryItemJpaRepository.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/categoryitem/CategoryItemPersistenceAdapter.java
Labels: enhancement

#123 [TEAM15-602] feat(gateway): Gateway Auth Filter 구현 (#122)
  fridge-service/fridge-adapters/src/main/resources/application-prod.yml
  gateway-service/gateway/build.gradle
  gateway-service/gateway/src/main/java/com/greenbowl/greenbowlserver/gateway/filter/AuthorizationHeaderFilter.java
  gateway-service/gateway/src/main/resources/application.yml
Labels: enhancement

#125 [TEAM15-609] Gateway JWT 환경변수 추가 (#124)
  fridge-service/fridge-adapters/src/main/resources/application.yml
Labels: configuration

#127 [TEAM15-610] Fridge Service Response 불필요한 응답값 제거 (#126)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/GetCategoryItemBySequenceResponse.java
Labels: enhancement

#128 [TEAM15-609] Gateway JWT 환경변수 추가 (#124)
  fridge-service/fridge-adapters/src/main/resources/application.yml
  gateway-service/gateway/src/main/resources/application.yml
Labels: configuration

#130 [TEAM15-613] fix(recommendation): 추천 서비스 요청 시 DB Connection Pool 부족 문제 해결
  docker-compose.yml
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/config/CommonConfig.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/CreateCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/CreateIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/DeleteCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/DeleteIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/GetCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/GetIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/UpdateIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/GetCategoryItemBySequenceResponse.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/categoryitem/CategoryItemJpaRepository.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/categoryitem/CategoryItemPersistenceAdapter.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/ingredient/IngredientPersistenceAdapter.java
  fridge-service/fridge-adapters/src/main/resources/application-prod.yml
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/aop/FridgeLoggingAspect.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/exception/NotFoundCategoryItemException.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/CreateCategoryItemService.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/CreateIngredientService.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/DeleteCategoryItemService.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/DeleteIngredientService.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/GetCategoryItemService.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/GetIngredientService.java
  fridge-service/fridge-application/src/main/java/com/greenbowl/greenbowlserver/fridge/application/service/UpdateIngredientService.java
  fridge-service/fridge-domain/src/main/java/com/greenbowl/greenbowlserver/fridge/domain/exception/DuplicateCategoryException.java
  gateway-service/gateway/build.gradle
  gateway-service/gateway/src/main/java/com/greenbowl/greenbowlserver/gateway/filter/AuthorizationHeaderFilter.java
  gateway-service/gateway/src/main/resources/application-prod.yml
  gateway-service/gateway/src/main/resources/application.yml
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/configuration/SwaggerConfig.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/controller/RecommendLlmRecipeController.java
  recommendation-service/recommendation-adapters/src/main/resources/application.yml
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/service/RecommendLlmMenuService.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/service/RecommendLlmRecipeService.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/configuration/SwaggerConfig.java
Labels: bug

#132 [TEAM15-613] fix(recommendation): 추천 서비스 요청 시 DB Connection Pool 부족 문제 해결
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/configuration/SwaggerConfig.java
  recipe-service/recipe-adapters/src/main/resources/application.yml
  recommendation-service/recommendation-adapters/src/main/resources/application.yml
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/service/RecommendLlmMenuService.java
  recommendation-service/recommendation-application/src/main/java/com/greenbowl/greenbowlserver/recommendation/service/RecommendLlmRecipeService.java
  user-service/user-adapters/src/main/java/com/greenbowl/greenbowlserver/user/adapter/in/web/configuration/SwaggerConfig.java
Labels: bug

#134 [TEAM15-621] Eureka Client service url 변경 (#133)
  fridge-service/fridge-adapters/src/main/resources/application-prod.yml
  gateway-service/gateway/src/main/resources/application-prod.yml
Labels: enhancement

#137 [TEAM15-624] fix(ai): [TEAM15-624] AI 서버와의 SSE 연결 중 조기에 연결이 종료되는 문제 해결
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/in/web/controller/RecommendLlmRecipeController.java
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/web/client/LlmStreamingClient.java
Labels: bug

#140 [TEAM15-635] feat(recipe): 클라이언트는 북마크 데이터의 상세 레시피 정보 저장 여부를 확인할 수 있다
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/response/GetDetailedRecipeResponse.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipePersistenceAdapter.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeRepository.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/service/RemoveRecipeService.java
  recommendation-service/recommendation-adapters/src/main/resources/application.yml
Labels: enhancement

#142 [TEAM15-638] feat(fridge): CategoryItem 및 Ingredient Response 수정 (#141)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/DeleteIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/GetCategoryItemBySequenceResponse.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/response/GetIngredientResponse.java
Labels: enhancement

#144 [TEAM15-639] feat(fridge): data.sql 내 오탈자 수정 (#143)
  fridge-service/fridge-adapters/src/main/resources/data.sql
Labels: enhancement

#146 [TEAM15-640] bug(fridge): Ingredient Update 조회 로직 수정 (#145)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/persistance/ingredient/IngredientPersistenceAdapter.java
Labels: bug

#148 [TEAM15-642] feat(fridge): controller request header 추가 (#147)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/CreateCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/CreateIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/DeleteCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/DeleteIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/GetCategoryItemController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/GetIngredientController.java
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/in/web/controller/UpdateIngredientController.java
Labels: enhancement

#151 [TEAM15-652] fix(fridge): Default Category 분류 값 표기 안되는 오류 (#150)
  fridge-service/fridge-adapters/src/main/java/com/greenbowl/greenbowlserver/fridge/adapter/out/mapper/FridgeJpaEntityToDomainMapper.java
Labels: bug

#153 [TEAM15-653] docs(gateway): gateway swagger config 설정 (#152)
  gateway-service/gateway/src/main/java/com/greenbowl/greenbowlserver/gateway/configuration/SwaggerConfig.java
Labels: documentation

#138 [TEAM15-626] fix(ai): AI 서버와의 SSE 연결 중 메모리 누수 문제 해결
  recommendation-service/recommendation-adapters/src/main/java/com/greenbowl/greenbowlserver/recommendation/adapter/out/web/client/LlmStreamingClient.java
Labels: bug

#161 [TEAM15-671] feat(recipe): 클라이언트는 북마크 저장 후 ID를 반환 받을 수 있다
  common/src/main/java/com/greenbowl/greenbowlserver/common/domain/exception/ExceptionMessage.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/in/web/controller/AddBookmarkRecipeController.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/in/usecase/CreateRecipeUseCase.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/port/out/SaveRecipePort.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/service/CreateRecipeService.java
Labels: enhancement

#162 [TEAM15-674] fix(recipe): 북마크의 상세 정보 수정 시 재료가 중복 저장되는 문제 해결
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeIngredientRepository.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipeJpaEntity.java
  recipe-service/recipe-adapters/src/main/java/com/greenbowl/greenbowlserver/recipe/adapter/out/persistence/recipe/RecipePersistenceAdapter.java
  recipe-service/recipe-application/src/main/java/com/greenbowl/greenbowlserver/recipe/service/ModifyRecipeService.java
Labels: bug
